### ISSUE TITLE
Switch to IsarDb from SQLite

### ISSUE THREAD

**Issue by mijiga** [geekquest/bankimoon#42]
### Justification
Unless there was a particular reason for using SQLite, let's migrate to [IsarDb](https://isar.dev) because: 

- It abstracts **a lot** of the technicalities to do with the creation and management of the DB and tables themselves
- It uses the concept of collections which is perfect for this use case - a simple app
- 1 & 2 make it beginner friendly
- It has full-text search and a filters built in
- It's arguably the standard which makes it easier to work with it's also not too far from Android's RoomDB which is also a standard hence soft landing for Android devs

**Comment by zikani03** [comment]
@mijiga  Great suggestion, especially sounds useful if we can find a smooth way to deal with migrations and search. Do you want to work on a PR for this?

**Comment by mijiga** [comment]
> @mijiga Great suggestion, especially sounds useful if we can find a smooth way to deal with migrations and search. Do you want to work on a PR for this?

@zikani03 yeah. I actually just finished one.
